# monq_gnx_params.py

# This is a parameters file generated by Geonomics
# (by the gnx.make_parameters_file() function).


                   #   ::::::          :::    :: :::::::::::#
             #::::::    ::::   :::      ::    :: :: ::::::::::: ::#
          #:::::::::     ::            ::   :::::::::::::::::::::::::#
        #::::::::::                      :::::::::: :::::: ::::::::  ::#
      #  : ::::  ::                    ::::  : ::    :::::::: : ::  :    #
     # GGGGG :EEEE: OOOOO   NN   NN   OOOOO   MM   MM IIIIII  CCCCC SSSSS #
    # GG     EE    OO   OO  NNN  NN  OO   OO  MM   MM   II   CC     SS     #
    # GG     EE   OO     OO NN N NN OO     OO MMM MMM   II   CC     SSSSSS #
    # GG GGG EEEE OO     OO NN  NNN OO     OO MM M MM   II   CC         SS #
    # GG   G EE    OO   OO  NN   NN  OO   OO  MM   MM   II   CC        SSS #
     # GGGGG :EEEE: OOOOO   NN   NN   OOOOO   MM   MM IIIIII  CCCCC SSSSS #
      #    : ::::::::               :::::::::: ::              ::  :   : #
        #:    :::::                    :::::: :::             :::::::  #
          #    :::                      :::::  ::              ::::: #
             #  ::                      ::::                      #
                   #                                        #
                      #  :: ::    :::             #

data_dir = ('/scratch/negishi/jeon96/monq/gnx/')


params = {
#-----------------------------------------------------------------------------#

#-----------------#
#--- LANDSCAPE ---# to be automatically generated later 
#-----------------#
    'landscape': {

    #------------#
    #--- main ---#
    #------------#
        'main': {
            #x,y (a.k.a. j,i) dimensions of the Landscape
            'dim':                      (258,291),
            #x,y resolution of the Landscape; automatically updated to the resolution of any GIS rasters that are read in for use as Layers
            'res':                      (1,1),
            #x,y coords of upper-left corner of the Landscape; utomatically updated to the resolution of any GIS rasters that are read in for use as Layers
            'ulc':                      (0,0),
            #projection of the Landscape
            'prj':                      None,
            }, # <END> 'main'

    #--------------#
    #--- layers ---#
    #--------------#
        'layers': {

            #layer name (LAYER NAMES MUST BE UNIQUE!)
            'hsm': {

        #-------------------------------------#
        #--- layer num. 0: init parameters ---#
        #-------------------------------------#

                #initiating parameters for this layer
                'init': {

                    #parameters for a 'file'-type Layer
                    'file': {
                        #</path/to/file>.<ext>
                        'filepath':       data_dir + 'monq_hsm.tif',
                        #minimum value to use to rescale the Layer to [0,1]
                        'scale_min_val':                0.000,
                        #maximum value to use to rescale the Layer to [0,1]
                        'scale_max_val':                1.000,
                        #decimal precision to use for coord-units (ulc & res)
                        'coord_prec':                   5,
                        #units of this file's variable
                        'units':                        'Suitability',

                        }, # <END> 'file'

                    }, # <END> 'init'

            #---------------------------------------#
            #--- layer num. 0: change parameters ---#
            #---------------------------------------#

                #landscape-change events for this Layer
                'change': {

                    0: {
                        #array or file for final raster of event, or directory
                        #of files for each stepwise change in event
                        'change_rast':      data_dir + 'hsm_ssp585/', # change the directory name as needed
                        #starting timestep of event
                        'start_t':          60,
                        #ending timestep of event
                        'end_t':            120,
                        #number of stepwise changes in event
                        'n_steps':          3,
                        }, # <END> event 0

                    }, # <END> 'change'

                }, # <END> layer num. 0

    #### NOTE: Individual Layers' sections can be copy-and-pasted (and
    #### assigned distinct keys and names), to create additional Layers.


            } # <END> 'layers'

        }, # <END> 'landscape'


#-----------------------------------------------------------------------------#

#-----------------#
#--- COMMUNITY ---#
#-----------------#
    'comm': {

        'species': {

            #species name (SPECIES NAMES MUST BE UNIQUE!)
            'MONQ': {

            #-----------------------------------#
            #--- spp num. 0: init parameters ---#
            #-----------------------------------#

                'init': {
                    #starting number of individs
                    'N':                500000, #11750
                    #carrying-capacity Layer name
                    'K_layer':          'hsm',
                    #multiplicative factor for carrying-capacity layer 
                    'K_factor':         500, # carrying-capacity per unit area converted from 1 bird/ha to 100 bird/km2 from Albers & Gehlbach (2000) and Brown (1976); or covey size?
                    }, # <END> 'init'

            #-------------------------------------#
            #--- spp num. 0: mating parameters ---#
            #-------------------------------------#

                'mating'    : {
                    #age(s) at sexual maturity (if tuple, female first)
                    'repro_age':                1,
                    #whether to assign sexes
                    'sex':                      False,
                    #ratio of males to females
                    'sex_ratio':                1/1,
                    #intrinsic growth rate
                    'R':                        0.2, # Based on R = b - d where d (annual mortality) = 0.8 from Birds of the World 
                    #intrinsic birth rate (MUST BE 0<=b<=1); # probability that an identified potential mating pair successfully produces offspring # NOTE: this may later need to be re-implemented to allow for spatial variation in intrinsic rate (i.e.. expression of a birth-rate raster), and/or for density-dependent birth as well as mortality
                    'b':                        0.5,
                    #expectation of distr of n offspring per mating pair
                    'n_births_distr_lambda':    4,
                    #whether n births should be fixed at n_births_dist_lambda
                    'n_births_fixed':           False,
                    #radius of mate-search area (None, for panmixia)
                    'mating_radius':            1.255,  # SM * 3 in relation to the layer dimension
                    #whether individs should choose nearest neighs as mates
                    'choose_nearest_mate':        False,
                    #whether mate-choice should be inverse distance-weighted
                    'inverse_dist_mating':      True,
                    }, # <END> 'mating'

            #----------------------------------------#
            #--- spp num. 0: mortality parameters ---#
            #----------------------------------------#

                'mortality'     : {
                    #maximum age
                    'max_age':                      3,
                    #min P(death) (MUST BE 0<=d_min<=1)
                    'd_min':                        0.4,
                    #max P(death) (MUST BE 0<=d_max<=1)
                    'd_max':                        1,
                    #width of window used to estimate local pop density 
                    'density_grid_window_width':    1.255, # SX * 3 in relation to the layer dimension
                    }, # <END> 'mortality'

            #---------------------------------------#
            #--- spp num. 0: movement parameters ---#
            #---------------------------------------#

                'movement': {
                    #whether or not the species is mobile
                    'move':                                 True,
                    #mode of distr of movement direction
                    'direction_distr_mu':                   0,
                    #concentration of distr of movement direction
                    'direction_distr_kappa':                0,
                    #1st param of distr of movement distance; # The values generated by the movement distribution will be expressed in units of raster-cell widths
                    'movement_distance_distr_param1':       -0.856, # Based on the average home range "2149.37 ha" (=21.4937 km2 -> 4.64 km) and the maximum home range "15751.36 ha" (=157.5136 km2 -> 12.55 km; assuming 99.5th percentile) from Greene et al. 2012
                    #2nd param of distr of movement distance
                    'movement_distance_distr_param2':       0.420, # Based on the average home range "2149.37 ha" (=21.4937 km2 -> 4.64 km) and the maximum home range "15751.36 ha" (=157.5136 km2 -> 12.55 km; assuming 99.5th percentile) from Greene et al. 2012
                    #movement distance distr to use ('lognormal','levy','wald')
                    'movement_distance_distr':              'lognormal',
                    #1st param of distr of dispersal distance; # The values generated by the dispersal distribution will be expressed in units of raster-cell widths
                    'dispersal_distance_distr_param1':      -0.851, # # Based on the mean movement "4.67 km" and the maximum movement "12.74 km" (assuming 99.5th percentile) from Greene et al. 2012
                    #2nd param of distr of dispersal distance
                    'dispersal_distance_distr_param2':      0.424, # Based on the mean movement "4.67 km" and the maximum movement "12.74 km" from Greene et al. 2012
                    #dispersal distance distr to use ('lognormal','levy','wald')
                    'dispersal_distance_distr':             'lognormal',
                    'move_surf'     : {
                        #move-surf Layer name
                        'layer':                'hsm',
                        #whether to use mixture distrs
                        'mixture':              True,
                        #concentration of distrs
                        'vm_distr_kappa':       12,
                        #length of approximation vectors for distrs
                        'approx_len':           500,
                        }, # <END> 'move_surf'

                    },    # <END> 'movement'


            #---------------------------------------------------#
            #--- spp num. 0: genomic architecture parameters ---#
            #---------------------------------------------------#

                'gen_arch': {
                    #file defining custom genomic arch
                    'gen_arch_file':            None,
                    #num of loci
                    'L':                        2256, # same number of genes of the SLiM script
                    #the lengths (in number of loci) of each of the chromosomes 
                    'l_c': [320,216,180,170,135,82,73,75,72,63,53,51,55,54,48,27,41,43,44,46,31,25,34,26,39,34,51,39,16,43,8,62],
                    #fixed starting allele freq; None/False -> rand; True -> 0.5
                    'start_p_fixed':            0.5,
                    #whether to start neutral locus freqs at 0
                    'start_neut_zero':          False,
                    #genome-wide per-base neutral mut rate (0 to disable)
                    'mu_neut':                  0, # calculated from the SLiM script, 3.13597726022324e-08 * 1000/(1000+231+2.31) -> disable
                    #genome-wide per-base deleterious mut rate (0 to disable)
                    'mu_delet':                 0, # calculated from the SLiM script, 3.13597726022324e-08 * 231/(1000+231+2.31) -> disable
                    #shape of distr of deleterious effect sizes
                    'delet_alpha_distr_shape':  0.186, # same as the SLiM script
                    #scale of distr of deleterious effect sizes
                    'delet_alpha_distr_scale':  0.01693, # calculated from the 1/10 selection coefficient of SLiM script (-0.00314833 = 0.186 * -0.01693)
                    #alpha of distr of recomb rates
                    'r_distr_alpha':            0.0001, # 1/10 of the SLiM script's
                    #beta of distr of recomb rates
                    'r_distr_beta':             None,
                    #whether loci should be dominant (for allele '1')
                    'dom':                      False,
                    #whether to allow pleiotropy
                    'pleiotropy':               False,
                    #custom fn for drawing recomb rates
                    'recomb_rate_custom_fn':    None,
                    #number of recomb paths to hold in memory
                    'n_recomb_paths_mem':       int(1e4),
                    #total number of recomb paths to simulate
                    'n_recomb_paths_tot':       int(1e5),
                    #num of crossing-over events (i.e. recombs) to simulate
                    'n_recomb_sims':            10_000,
                    #whether to generate recombination paths at each timestep
                    'allow_ad_hoc_recomb':      True,
                    #whether to jitter recomb bps, to correctly track num_trees
                    'jitter_breakpoints':       False,
                    #whether to save mutation logs
                    'mut_log':                  False,
                    #whether to use tskit (to record ARG and spatial pedigree)
                    'use_tskit':                False,
                    #time step interval for simplification of tskit tables
                    'tskit_simp_interval':      10,

                    'traits': {

                        #-------------------------#
                        #---trait 0 parameters ---#
                        #-------------------------#
                        #trait name (TRAIT NAMES MUST BE UNIQUE!)
                        'trait_suit': {
                            #trait-selection Layer name
                            'layer':                'hsm',
                            #phenotypic selection coefficient
                            'phi':                  1.00,
                            #number of loci underlying trait
                            'n_loci':               4,  # calculated from the SLiM script, 2256 * 2.31/(1000+231+2.31)
                            #mutation rate at loci underlying trait
                            'mu':                   0, # calculated from the SLiM script, 3.13597726022324e-09 * 2.31/(1000+231+2.31)
                            #mean of distr of effect sizes
                            'alpha_distr_mu' :      0.1, # same as "S_MOR" of m13 in the SLiM script
                            #variance of distr of effect size
                            'alpha_distr_sigma':    0,
                            #max allowed magnitude for an alpha value
                            'max_alpha_mag':        None,
                            #curvature of fitness function
                            'gamma':                1,
                            #whether the trait is universally advantageous
                            'univ_adv':             True
                            }, # <END> trait 0

                        

    #### NOTE: Individual Traits' sections can be copy-and-pasted (and
    #### assigned distinct keys and names), to create additional Traits.


                        }, # <END> 'traits'

                    }, # <END> 'gen_arch'

# can add demographic change parameters

                }, # <END> spp num. 0



    #### NOTE: individual Species' sections can be copy-and-pasted (and
    #### assigned distinct keys and names), to create additional Species.


            }, # <END> 'species'

        }, # <END> 'comm'


#-----------------------------------------------------------------------------#

#-------------#
#--- MODEL ---#
#-------------#
    'model': {
        #total Model runtime (in timesteps)
        'T':            150,
        #min burn-in runtime (in timesteps)
        'burn_T':       30,
        #seed number
        'num':          123,
        #time step interval for simplication of tskit tables
        'tskit_simp_interval':      10,


        #-----------------------------#
        #--- iterations parameters ---#
        #-----------------------------#
        'its': {
            #num iterations
            'n_its':            2,
            #whether to randomize Landscape each iteration
            'rand_landscape':   False,
            #whether to randomize Community each iteration
            'rand_comm':        False,
            #whether to randomize GenomicArchitectures each iteration
            'rand_genarch':    True,
            #whether to burn in each iteration
            'repeat_burn':      False,
            }, # <END> 'iterations'
            # can add Data and Stats parameters


        #----------------------------------#
        #--- data-collection parameters ---#
        #----------------------------------#
        'data': {
            'sampling': {
                #sampling scheme {'all', 'random', 'point', 'transect'}
                'scheme':               'random',
                #sample size at each point, for point & transect sampling
                'n':                    10000,
                #coords of collection points, for point sampling
                'points':               None,
                #coords of transect endpoints, for transect sampling
                'transect_endpoints':   None,
                #num points along transect, for transect sampling
                'n_transect_points':    None,
                #collection radius around points, for point & transect sampling
                'radius':               None,
                #when to collect data
                'when':                 10,
                #whether to save current Layers when data is collected
                'include_landscape':    False,
                #whether to include fixed loci in VCF files
                'include_fixed_sites':  False,
                },
            'format': {
                #format for genetic data {'vcf', 'fasta'}
                'gen_format':           ['vcf', 'fasta'],
                #format for vector geodata {'csv', 'shapefile', 'geojson'}
                'geo_vect_format':      'csv',
                #format for raster geodata {'geotiff', 'txt'}
                'geo_rast_format':      'geotiff',
                #format for file listing non-neut loci (if 'csv', will be saved)
                'nonneut_loc_format': 'csv',
                },
            }, #<END> 'data'


        #-----------------------------------#
        #--- stats-collection parameters ---#
        #-----------------------------------#
        'stats': {
            #number of individs at time t
            'Nt': {
                #whether to calculate
                'calc':     True,
                #calculation frequency (in timesteps)
                'freq':     1,
                },
            #heterozgosity
            'het': {
                #whether to calculate
                'calc':     True,
                #calculation frequency (in timesteps)
                'freq':     1,
                #whether to mean across sampled individs
                'mean': True,
                },
            #minor allele freq
            'maf': {
                #whether to calculate
                'calc':     True,
                #calculation frequency (in timesteps)
                'freq':     1,
                },
            #mean fitness
            'mean_fit': {
                #whether to calculate
                'calc':     True,
                #calculation frequency (in timesteps)
                'freq':     1,
                },
            #linkage disequilibirum
            'ld': {
                #whether to calculate
                'calc':     False,
                #calculation frequency (in timesteps)
                'freq':     1,
                },
            }, # <END> 'stats'
            
        } # <END> 'model'

    } # <END> params